### ISSUE TITLE
Unable to auto start images

### ISSUE THREAD

**Issue by gregbty** [JetBrains/teamcity-azure-plugin#7] opened 2015-06-16 23:51 UTC
When there are builds in the queue the system never tries to auto a cloud image. I am forced to start a VM myself via the Cloud page. I did notice that the VM image started by the image lists the correct agent requirements while the image does not. I can provide screenshots if needed.

**Comment by paksv** [comment] 2015-07-21 11:37
duplicate of #9

**Closed by paksv** 2015-07-21 11:37 UTC
