### ISSUE TITLE
Start/Stop functionality for existing Azure VM doesn't work

### ISSUE THREAD

**Issue by sshiman** [JetBrains/teamcity-azure-plugin#8] opened 2015-07-02 13:44 UTC
Start/Stop functionality - doesn't work with currently existing Virtual Machine Instance. 

After TC starts the instance before the build and stops after a build on idle timeout (I set the value of "1") - then it would not start any subsequent build anymore again!?.

My setup for TC on Windows 8.1 (TeamCity Professional 9.0.4 (build 32407)) is -> 2 "in-house" agents + 1 Azure agent. 
I have 2 pools setup - "local" and "Azure" ones with 2 and 1 agent associated with accordingly.

My project is assigned only to Azure pool (of one instance) on the Pools tab. 

I can provide screenshots if needed.

**Comment by paksv** [comment] 2015-07-21 11:37
duplicate of #9

**Closed by paksv** 2015-07-21 11:37 UTC
